# Cleaning notebook

Aylie Lapierre Nagler <br>
COMP 2040 <br>
April 21, 2026

The first step is to narrow down the possible analytical questions to provide cleaning guidance:

The insights I will be exploring in this data pertain to the patterns in the location of permits:
1. Are there hotspots for certain types of construction?
2. Are there any temporal patterns indicating the geographical direction of growth in the city?

Import modules:

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Import your helper module
import sys
sys.path.insert(0, '..')
from src.helpers import *

Load data:

In [4]:
# Load data
df = pd.read_csv('../data/building-permits.csv', dtype={23: str, 24: str, 25: str, 26: str})

### Remove Time from *issue_date*

Issue date includes time which is always set to midnight. This is not meaningful and will be removed for clarity:

In [5]:
# Display column for demonstration of issue
df['issue_date'].head()

0    2010-02-01T00:00:00.000
1    2010-02-16T00:00:00.000
2    2010-03-19T00:00:00.000
3    2010-03-23T00:00:00.000
4    2010-04-13T00:00:00.000
Name: issue_date, dtype: object

In [7]:
# Remove time w/ remove_time() helper function
df['issue_date'] = remove_time(df['issue_date'])

In [8]:
# Confirm proper application
df['issue_date'].head()

0   2010-02-01
1   2010-02-16
2   2010-03-19
3   2010-03-23
4   2010-04-13
Name: issue_date, dtype: datetime64[ns]

### Remove time from *final_date*

Similar to *issue_date*, *final_date* includes messy time information that does not carry any meaning. As such, the time will be removed from this column as well:

In [9]:
# Display column for demonstration of issue
df['final_date'].head()

0    2012-01-11T00:00:00.000
1    2011-05-11T00:00:00.000
2    2010-10-27T00:00:00.000
3    2011-01-07T00:00:00.000
4    2011-07-28T00:00:00.000
Name: final_date, dtype: object

In [10]:
# Remove time w/ remove_time() helper function
df['final_date'] = remove_time(df['final_date'])

In [11]:
# Confirm proper application
df['final_date'].head()

0   2012-01-11
1   2011-05-11
2   2010-10-27
3   2011-01-07
4   2011-07-28
Name: final_date, dtype: datetime64[ns]

### Remove time from *application_received_date*

Similar to *issue_date* and *final_date*, *application_received_date* includes messy time information that does not carry any meaning. As such, the time will be removed from this column as well:

In [12]:
# Display column for demonstration of issue
df['application_received_date'].head()

0    2010-02-01T00:00:00.000
1    2010-02-16T00:00:00.000
2    2010-03-19T00:00:00.000
3    2010-03-23T00:00:00.000
4    2010-04-13T00:00:00.000
Name: application_received_date, dtype: object

In [13]:
# Remove time w/ remove_time() helper function
df['application_received_date'] = remove_time(df['application_received_date'])

In [14]:
# Confirm proper application
df['final_date'].head()

0   2012-01-11
1   2011-05-11
2   2010-10-27
3   2011-01-07
4   2011-07-28
Name: final_date, dtype: datetime64[ns]

### Assess whether filling in missing values in columns pertaining to address is worth it:

This data contains a complete *address* column, as well as *street_number*, *street_name*, *street_type*, and *street_direction* columns which store address data more atomically. The address column only has 3 missing values, whereas the more atomoic versions of it have a minimum of 272 missing values. If data in the *address* column is mostly stored in a consistent structure, it will be used to fill the missing values in other columns pertaining to address. If it is not stored in a consistent structure, geopy will be used to get coordinates instead:

In [15]:
# Use sample to get an idea of data structure
df['address'].sample(25)

5568              35 Lou Peltier CRES
133793                  531 Camden Pl
54004     2211 McPhillips ST Unit 203
59689                  34 Longspur RD
102536                40 Dunedin COVE
102957               1 Blackberry BAY
101636            235 Strathmillan RD
62427                1471 Elgin AVE W
120736                22 Darbrett BAY
33231              456 Smithfield AVE
86995                   19 Cornell DR
75159                46 Hastings BLVD
21792             66 Riverhaven GROVE
56304                 60 Hillbrook DR
76738                 78 Rowntree AVE
85204                 108 Pilgrim AVE
65550            129 Bonaventure DR E
115237                218 Brooklyn ST
145361         342 Granite Grove Road
121662                365 Main Street
53871                 781 Crescent DR
126135                87 Harrowby AVE
61074             97 Bonaventure DR E
85834                   33 Camira WAY
76024         93 Swindon WAY Unit 211
Name: address, dtype: object

Observations:
- The first 'word' is always the street number
- The second word is always related to the street name
- Some street names are 2 (+?) words long, meaning the third word is not consistent
- The last word is either the street type or the unit number, with the second last word sometimes being 'UNIT' or 'Unit'
- Some rows have units that are names instead of numbers
- Some rows have dashes in the unit number
- Some of street types are all-caps abbreviations and others are the full word in title caps
- Some rows have 'Level' specified as the second last word, with the level number being the last row
- Some rows have street numbers that include a slash (e.g., 650/652 or 364 / 364)
- Some rows have 'building' and the building letter or number after the street type
- Some rows have an extra space (data is messy)

This data is not consistent at all. Coordinates will offer similar insights at less of a time cost. These address columns will be dropped since they are not needed to answer my analysis questions.

In [16]:
df = df.drop(columns=['street_number', 'street_name', 'street_type', 'street_direction'])

### Get coordinates from *address* column using Googel Maps API

Test with known coordinates: 
- Address: 160 Princess St, Winnipeg, Manitoba R3B 1K9, CA
- Coordinates: N49.90023, W97.14111 (Manitoba Historical Archives, 2024)

In [11]:
pip install googlemaps

Requirement already satisfied: googlemaps in c:\users\aylie\anaconda3\lib\site-packages (4.10.0)
Requirement already satisfied: requests<3.0,>=2.20.0 in c:\users\aylie\anaconda3\lib\site-packages (from googlemaps) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\aylie\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\aylie\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\aylie\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\aylie\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2026.1.4)
Note: you may need to restart the kernel to use updated packages.

In [12]:
import googlemaps
gmaps = googlemaps.Client(key='AIzaSyDPg-7ZNC4wmhVnNKMNQ6_NTPkI-tUkWOQ')

In [13]:
test_gmap = gmaps.geocode('160 Princess St' + ", Winnipeg, MB, Canada")
test_lat = test_gmap[0]['geometry']['location']['lat']
test_long = test_gmap[0]['geometry']['location']['lng']

print(test_lat, ",", test_long)

49.9003569 , -97.14143779999999

It is functioning properly. There are only 355 missing rows in the longitude and latitude coordinate columns. The Google Maps API will be applied to only those rows to conserve API tokens.

In [26]:
# Run helper function to fill in missing coordinates using Google Maps API
df, fails = extract_coords(df)

# Check fails list to see if any rows were not updated
fails

[]

There were no fails! Now I will check the number of missing values in both coordinate columns to confirm the function ran properly. I am expecting 0 missing values since none of the rows failed.

In [27]:
print(f"Missing values in x_coordinate_nad83: {df['x_coordinate_nad83'].isna().sum()}\n"
      f"Missing values in y_coordinate_nad83: {df['y_coordinate_nad83'].isna().sum()} ")

Missing values in x_coordinate_nad83: 0
Missing values in y_coordinate_nad83: 0

### Rename *x_coordinate_nad83* and *y_coordinate_nad83*

Latitude and Longitude are more readable

In [28]:
df = df.rename(columns={'x_coordinate_nad83': 'latitude', 'y_coordinate_nad83': 'longitude'})

### Drop *location*

Location contains the latitude and longitude coordinates paired up in tuple formatting. The latitude and longitude store this information more atomically and will be kept:

In [17]:
df = df.drop(columns='location')

### Drop *ward* column

Wards can change, whereas neighbourhoods contain similar information but are much more stable. As such, wards will be dropped and neighbourhood_name will be kept:

In [18]:
df = df.drop(columns='ward')

### Drop *neighbourhood_number* column

Neighbourhood number does not carry any inherent meaning, and storing neighbourhoods numerically does not carry any computational value. neighbourhood_name will be kept instead:

In [19]:
df = df.drop(columns='neighbourhood_number')

### Drop *point* column

*point* contains coordinates. It has 355 missing values and is redundant to *latitude* and *longitude* columns.

In [20]:
df = df.drop(columns='point')

### Drop *parent_permit_number* column

This is not relevant to my analysis questions which focus on temporal and spatial trends.

In [21]:
df = df.drop(columns='parent_permit_number')

### Investigate string suffix on *permit_number*

In [22]:
get_suffix(df['permit_number'])

{'AS',
 'CS',
 'EH',
 'HO',
 'MP',
 'MU',
 'OP',
 'PE',
 'PI',
 'PU',
 'RE',
 'RP',
 'SA',
 'SP',
 'TA',
 'TB'}

These likely denote the type of permit.:

In [23]:
df['permit_type'].unique()

array(['Housing', 'Multi-Residential', 'Accessory Structures',
       'Commercial Storage', 'Office', 'Health Services / Education',
       'Temporary Building Renewals', 'Sign', 'Retail',
       'Personal Services', 'Temporary Approval',
       'Recreation / Entertainment', 'General Public / Institutional',
       'Manufacturing', 'Public Utility', 'Safety / Protection'],
      dtype=object)

Many of the suffixes align, e.g.:
- HO: Housing
- CS: Commerical Storage
- PU: Public Utility <br><br>

These are communicating the same thing, however, dropping one or the other is not warranted since altering the suffix on *permit_number* would make it unsearchable in the full database, and without *permit_type* the suffixes would be meaningless. Both will be kept.

### Check for outliers

In [29]:
outliers(df)

,dwelling_units_created,dwelling_units_lost,latitude,longitude
count,29899.000000,3703.000000,504.000000,355.000000
percentage,18.932045,2.344739,0.319133,0.224786

The series pertaining to dwellings created/lost mostly contain values of 0. This function uses the IQR method to find outliers, which assumes a normal distribution, which these columns do not have. The outliers here are not *true* outliers in that they are not cause for concern or outside of expected values. As for latitude and longitude, the percentage of outliers is less than 0.5% which is basically negligible. None of these are cause for concern.

### Final columns after cleaning

In [30]:
# Get columns and data type in table format (2 cols)
split_columns(df)

,Column Names,Data Types,Column Names (cont.),Data Types (cont.)
0,issue_date,datetime64[ns],latitude,float64
1,permit_number,object,longitude,float64
2,permit_group,object,includes_secondary_suite,object
3,permit_type,object,adding_secondary_suite,object
4,sub_type,object,removing_secondary_suite,object
5,work_type,object,pool_type,object
6,unit_type,object,type_of_structure,object
7,unit_number,object,application_received_date,datetime64[ns]
8,neighbourhood_name,object,status,object
9,community,object,final_date,datetime64[ns]
10,applicant_business_name,object,economic_development_category,object
11,dwelling_units_created,int64,major_project,object
12,dwelling_units_lost,int64,address,object

### Save cleaned dataframe to CSV

In [31]:
df.to_csv('../data/building-permits-clean.csv', index=False)